import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type Language = 'vi' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Vietnamese translations
const vi: Record<string, string> = {
  // Common
  'common.search': 'Tìm kiếm hóa đơn, khách hàng...',
  'common.loading': 'Đang tải...',
  'common.noData': 'Không có dữ liệu',
  'common.save': 'Lưu',
  'common.cancel': 'Hủy',
  'common.delete': 'Xóa',
  'common.edit': 'Sửa',
  'common.add': 'Thêm',
  'common.view': 'Xem',
  'common.close': 'Đóng',
  'common.confirm': 'Xác nhận',
  'common.back': 'Quay lại',
  'common.next': 'Tiếp theo',
  'common.submit': 'Gửi',
  'common.export': 'Xuất',
  'common.import': 'Nhập',
  'common.filter': 'Lọc',
  'common.reset': 'Đặt lại',
  'common.all': 'Tất cả',
  'common.status': 'Trạng thái',
  'common.actions': 'Hành động',
  'common.date': 'Ngày',
  'common.amount': 'Số tiền',
  'common.total': 'Tổng',
  'common.details': 'Chi tiết',
  'common.settings': 'Cài đặt',
  'common.help': 'Trợ giúp',
  'common.logout': 'Đăng xuất',

  // Header
  'header.alerts': 'Cảnh báo',
  'header.unreadAlerts': 'cảnh báo chưa xác nhận',
  'header.noAlerts': 'Không có cảnh báo',
  'header.viewAllAlerts': 'Xem tất cả cảnh báo',
  'header.high': 'Cao',
  'header.medium': 'Trung bình',
  'header.low': 'Thấp',

  // Sidebar - Main navigation
  'nav.cfoOverview': 'Tổng quan CFO',
  'nav.dashboard': 'Dashboard',
  'nav.cashForecast': 'Cash Flow Forecast',
  'nav.cashFlowDirect': 'Dòng tiền trực tiếp',
  'nav.workingCapital': 'Tối ưu vốn lưu động',
  'nav.cashConversion': 'Cash Conversion Cycle',
  'nav.retailOps': 'Vận hành bán lẻ',
  'nav.inventoryAging': 'Tuổi tồn kho',
  'nav.promotionROI': 'ROI Khuyến mãi',
  'nav.supplierPayments': 'Thanh toán NCC',

  'nav.strategyDecision': 'Chiến lược & Quyết định',
  'nav.executiveSummary': 'Executive Summary',
  'nav.capitalAllocation': 'Phân bổ vốn',
  'nav.riskDashboard': 'Risk Dashboard',
  'nav.decisionSupport': 'Hỗ trợ quyết định',

  'nav.financialReports': 'Báo cáo tài chính',
  'nav.plReport': 'Báo cáo P&L',
  'nav.analysis': 'Phân tích tổng hợp',
  'nav.budgetVsActual': 'Budget vs Actual',
  'nav.varianceAnalysis': 'Phân tích chênh lệch',
  'nav.boardReports': 'Báo cáo HĐQT',

  'nav.planSimulation': 'Kế hoạch & Mô phỏng',
  'nav.scenario': 'Kịch bản & What-If',
  'nav.rollingForecast': 'Rolling Forecast',
  'nav.strategicInitiatives': 'Sáng kiến chiến lược',

  'nav.arAp': 'AR/AP',
  'nav.invoiceManagement': 'Quản lý hóa đơn',
  'nav.arOperations': 'AR Operations',
  'nav.apOverview': 'AP Overview',
  'nav.creditDebitNotes': 'CN/DN Tracking',
  'nav.reconciliation': 'Đối soát',

  'nav.salesChannels': 'Kênh bán hàng',
  'nav.channelAnalytics': 'Phân tích kênh',
  'nav.unitEconomics': 'Unit Economics',

  'nav.dataHub': 'Data Hub',
  'nav.dataCenter': 'Trung tâm dữ liệu',
  'nav.etlRules': 'Quy tắc ETL',

  'nav.taxCompliance': 'Thuế & Tuân thủ',
  'nav.taxTracking': 'Tax Compliance',
  'nav.covenantTracking': 'Covenant Tracking',

  'nav.alerts': 'Cảnh báo',

  'nav.admin': 'Quản trị',
  'nav.companyManagement': 'Quản lý công ty',
  'nav.members': 'Thành viên',
  'nav.rbac': 'Phân quyền RBAC',
  'nav.auditLog': 'Nhật ký hoạt động',

  'nav.api': 'API',

  'nav.integrationGuide': 'Hướng dẫn tích hợp',
  'nav.formulas': 'Công thức tính',
  'nav.formulasOverview': 'Tổng hợp công thức',
  'nav.formulaSettings': 'Cài đặt tham số',
  'nav.superAdmin': 'Super Admin',
  'nav.tenantManagement': 'Quản lý Tenants',
  'nav.userManagement': 'Quản lý Users',
  'nav.platformSettings': 'Cài đặt Platform',

  // Auth
  'auth.signIn': 'Đăng nhập',
  'auth.signUp': 'Đăng ký',
  'auth.email': 'Email',
  'auth.password': 'Mật khẩu',
  'auth.confirmPassword': 'Xác nhận mật khẩu',
  'auth.fullName': 'Họ và tên',
  'auth.forgotPassword': 'Quên mật khẩu?',
  'auth.noAccount': 'Chưa có tài khoản?',
  'auth.hasAccount': 'Đã có tài khoản?',

  // Dashboard
  'dashboard.title': 'Bảng điều khiển CFO',
  'dashboard.totalRevenue': 'Tổng doanh thu',
  'dashboard.netProfit': 'Lợi nhuận ròng',
  'dashboard.cashBalance': 'Số dư tiền mặt',
  'dashboard.accountsReceivable': 'Phải thu',
  'dashboard.refreshData': 'Làm mới dữ liệu',

  // Executive Summary
  'exec.subtitle': 'Tổng quan tài chính dành cho CEO/Board - cập nhật real-time',
  'exec.healthScore': 'Financial Health Score',
  'exec.healthDescription': 'Đánh giá sức khỏe tài chính theo 6 chiều',
  'exec.points': 'điểm',
  'exec.statusGood': 'Tốt',
  'exec.statusWarning': 'Trung bình',
  'exec.statusCritical': 'Cần cải thiện',
  'exec.goodMetrics': 'Chỉ số tốt',
  'exec.needsMonitoring': 'Cần theo dõi',
  'exec.needsImprovement': 'Cần cải thiện',
  'exec.revenueMTD': 'Doanh thu tháng',
  'exec.cashPosition': 'Vị thế tiền mặt',
  'exec.runway': 'Runway',
  'exec.months': 'tháng',
  'exec.minThreshold': 'Ngưỡng tối thiểu',
  'exec.target': 'mục tiêu',
  'exec.quickWins': 'Cơ hội nhanh',
  'exec.quickWinsDesc': 'Cơ hội tiết kiệm/tăng revenue - tính từ dữ liệu thực',
  'exec.noQuickWins': 'Tuyệt vời! Không có quick win cần xử lý',
  'exec.totalPotential': 'Tổng tiềm năng thu hồi',
  'exec.riskAlerts': 'Cảnh báo rủi ro',
  'exec.riskAlertsDesc': 'Các rủi ro tài chính cần lưu ý',
  'exec.noRiskAlerts': 'Không có cảnh báo rủi ro nào',
  'exec.effortLow': 'Dễ thực hiện',
  'exec.effortMedium': 'Trung bình',
  'exec.effortHigh': 'Phức tạp',
  'exec.reduceRisk': 'Giảm rủi ro',
  // Health dimensions
  'exec.dimLiquidity': 'Thanh khoản',
  'exec.dimReceivables': 'Công nợ',
  'exec.dimProfitability': 'Lợi nhuận',
  'exec.dimEfficiency': 'Hiệu quả',
  'exec.dimGrowth': 'Tăng trưởng',
  'exec.dimStability': 'Ổn định',

  // Covenant Tracking
  'covenant.title': 'Theo dõi Covenant',
  'covenant.subtitle': 'Giám sát tuân thủ cam kết tài chính với ngân hàng',
  'covenant.addCovenant': 'Thêm Covenant',
  'covenant.compliant': 'Tuân thủ',
  'covenant.warning': 'Cảnh báo',
  'covenant.breached': 'Vi phạm',
  'covenant.lender': 'Ngân hàng',
  'covenant.type': 'Loại',
  'covenant.threshold': 'Ngưỡng',
  'covenant.current': 'Hiện tại',
  'covenant.margin': 'Margin',
  'covenant.measurementHistory': 'Lịch sử đo lường',

  // CFO Dashboard
  'cfo.title': 'Thanh khoản & Tiền mặt',
  'cfo.subtitle': 'Liquidity & Cash Overview',
  'cfo.pageTitle': 'Tổng quan CFO | Bluecore Finance',
  'cfo.pageDesc': 'Dashboard tài chính cho CFO - Thanh khoản, tiền mặt, công nợ và dự báo',
  'cfo.refreshData': 'Cập nhật dữ liệu',
  'cfo.cashToday': 'Tiền mặt hôm nay',
  'cfo.cashRunway': 'Cash Runway',
  'cfo.cashNext7Days': 'Tiền mặt 7 ngày tới',
  'cfo.overdueAR': 'Tổng AR quá hạn',
  'cfo.ccc': 'Cash Conversion Cycle',
  'cfo.days': 'ngày',
  'cfo.dso': 'DSO',
  'cfo.grossMargin': 'Gross Margin',
  'cfo.ebitdaMargin': 'EBITDA Margin',
  'cfo.ebitda': 'EBITDA',
  'cfo.thisPeriod': 'kỳ này',
  'cfo.vsYesterday': 'vs hôm qua',
  'cfo.burnPerMonth': 'burn/tháng (triệu)',
  'cfo.notEnoughData': 'Chưa đủ dữ liệu',
  'cfo.chartError': 'Không thể tải biểu đồ',

  // Cash Forecast
  'cashForecast.title': 'Cash Flow Forecast',
  'cashForecast.subtitle': 'Dự báo dòng tiền chi tiết theo ngày hoặc tuần',
  'cashForecast.pageDesc': 'Dự báo dòng tiền hàng ngày và hàng tuần với AI insights và phân tích kịch bản',
  'cashForecast.daily': 'Theo ngày (90 ngày)',
  'cashForecast.weekly': 'Theo tuần (13 tuần)',

  // Cash Flow Direct
  'cashDirect.title': 'Dòng tiền trực tiếp',
  'cashDirect.subtitle': 'Direct Cash Flow Statement',
  'cashDirect.totalInflow': 'Tổng thu',
  'cashDirect.totalOutflow': 'Tổng chi',
  'cashDirect.netChange': 'Thay đổi ròng',
  'cashDirect.runway': 'Cash Runway',
  'cashDirect.burnRate': 'Burn',
  'cashDirect.perMonth': '/tháng',
  'cashDirect.operating': 'Hoạt động kinh doanh',
  'cashDirect.investing': 'Hoạt động đầu tư',
  'cashDirect.financing': 'Hoạt động tài chính',
  'cashDirect.noData': 'Chưa có dữ liệu dòng tiền',
  'cashDirect.addData': 'Thêm báo cáo dòng tiền để phân tích',
  'cashDirect.chart': 'Biểu đồ',
  'cashDirect.detail': 'Chi tiết',
  'cashDirect.trendTitle': 'Xu hướng dòng tiền theo kỳ',
  'cashDirect.closingBalance': 'Số dư tiền cuối kỳ',
  'cashDirect.detailTitle': 'Chi tiết dòng tiền theo kỳ',
  'cashDirect.period': 'Kỳ',
  'cashDirect.type': 'Loại',
  'cashDirect.actual': 'Thực tế',
  'cashDirect.forecast': 'Dự báo',
  'cashDirect.fromCustomers': 'Thu từ KH',
  'cashDirect.toSuppliers': 'Chi NCC',
  'cashDirect.toEmployees': 'Chi lương',
  'cashDirect.cfOperating': 'CF kinh doanh',
  'cashDirect.cfInvesting': 'CF đầu tư',
  'cashDirect.cfFinancing': 'CF tài chính',
  'cashDirect.endingBalance': 'Số dư cuối',
  'cashDirect.months': 'tháng',
  'cashDirect.million': 'triệu',

  // Working Capital
  'workingCapital.title': 'Tối ưu vốn lưu động',
  'workingCapital.subtitle': 'Phân tích và tối ưu chu kỳ tiền mặt (Cash Conversion Cycle)',
  'workingCapital.formulas': 'Công thức tính',
  'workingCapital.dso': 'DSO',
  'workingCapital.dsoFull': 'DSO (Days Sales Outstanding)',
  'workingCapital.dsoFormula': '= (Phải thu / Doanh thu) × Số ngày',
  'workingCapital.dsoDesc': 'Số ngày thu tiền từ khách hàng',
  'workingCapital.dio': 'DIO',
  'workingCapital.dioFull': 'DIO (Days Inventory Outstanding)',
  'workingCapital.dioFormula': '= (Tồn kho / COGS) × Số ngày',
  'workingCapital.dioDesc': 'Số ngày tồn kho trước khi bán',
  'workingCapital.dpo': 'DPO',
  'workingCapital.dpoFull': 'DPO (Days Payable Outstanding)',
  'workingCapital.dpoFormula': '= (Phải trả / Mua hàng) × Số ngày',
  'workingCapital.dpoDesc': 'Số ngày thanh toán cho NCC',
  'workingCapital.ccc': 'CCC (Chu kỳ tiền mặt)',
  'workingCapital.cccFormula': '= DSO + DIO - DPO',
  'workingCapital.days': 'ngày',
  'workingCapital.target': 'Mục tiêu',
  'workingCapital.inventoryDays': 'Ngày tồn kho',
  'workingCapital.improving': 'Đang cải thiện',
  'workingCapital.worsening': 'Đang xấu đi',
  'workingCapital.stable': 'Ổn định',
  'workingCapital.potentialRelease': 'Tiềm năng giải phóng vốn',
  'workingCapital.ifTargetMet': 'Nếu đạt mục tiêu',
  'workingCapital.cccAnalysis': 'Phân tích CCC',
  'workingCapital.current': 'Hiện tại',
  'workingCapital.cccTrend': 'Xu hướng CCC',
  'workingCapital.cccTrendDesc': 'Diễn biến chu kỳ tiền mặt theo thời gian',
  'workingCapital.noTrendData': 'Chưa có dữ liệu xu hướng',
  'workingCapital.ar': 'Phải thu khách hàng (AR)',
  'workingCapital.inventory': 'Tồn kho',
  'workingCapital.ap': 'Phải trả nhà cung cấp (AP)',
  'workingCapital.turnover': 'Vòng quay',
  'workingCapital.recommendations': 'Khuyến nghị tối ưu',
  'workingCapital.recommendationsDesc': 'Các hành động để cải thiện vốn lưu động',

  // Cash Conversion Cycle
  'ccc.title': 'Cash Conversion Cycle (CCC)',
  'ccc.subtitle': 'Phân tích vòng quay vốn lưu động: DSO + DIO - DPO',
  'ccc.loadError': 'Không thể tải dữ liệu Cash Conversion Cycle',
  'ccc.formulas': 'Công thức tính',
  'ccc.dsoDesc': 'Thời gian thu hồi công nợ',
  'ccc.dioDesc': 'Thời gian tồn kho',
  'ccc.dpoDesc': 'Thời gian thanh toán NCC',
  'ccc.good': 'Tốt',
  'ccc.high': 'Cao',
  'ccc.low': 'Thấp',
  'ccc.vsIndustry': 'So với ngành',
  'ccc.betterBy': 'Tốt hơn',
  'ccc.slowerBy': 'Chậm hơn',
  'ccc.industryBenchmark': 'Benchmark ngành',
  'ccc.receivables': 'Phải thu',
  'ccc.inventoryValue': 'Tồn kho',
  'ccc.payables': 'Phải trả',
  'ccc.benchmark': 'Benchmark',
  'ccc.trendTitle': 'Xu hướng CCC',
  'ccc.trendDesc': 'Theo dõi các thành phần qua thời gian',
  'ccc.noTrendData': 'Chưa có dữ liệu xu hướng',
  'ccc.wcImpact': 'Tác động Working Capital',
  'ccc.wcImpactDesc': 'Vốn lưu động đang bị chiếm dụng',
  'ccc.capitalTied': 'Vốn đang bị kẹt',

  // Inventory Aging
  'inventory.title': 'Phân tích tuổi tồn kho',
  'inventory.subtitle': 'Inventory Aging Analysis',
  'inventory.totalSKU': 'Tổng SKU',
  'inventory.totalValue': 'Tổng giá trị',
  'inventory.avgAge': 'Tuổi TB',
  'inventory.days': 'ngày',
  'inventory.slowMoving': 'Tồn chậm (>90 ngày)',
  'inventory.noData': 'Chưa có dữ liệu tồn kho',
  'inventory.noDataDesc': 'Import dữ liệu tồn kho để xem phân tích tuổi hàng',
  'inventory.valueByAge': 'Phân bổ giá trị theo tuổi',
  'inventory.qtyValueByBucket': 'Số lượng & Giá trị theo bucket',
  'inventory.quantity': 'Số lượng',
  'inventory.valueMillion': 'Giá trị (triệu)',
  'inventory.detailByAge': 'Chi tiết theo nhóm tuổi',
  'inventory.slowMovingItems': 'Hàng tồn chậm (>90 ngày)',
  'inventory.sku': 'SKU',
  'inventory.productName': 'Tên sản phẩm',
  'inventory.category': 'Danh mục',
  'inventory.value': 'Giá trị',
  'inventory.ageDays': 'Tuổi (ngày)',

  // Promotion ROI
  'promo.title': 'ROI Khuyến mãi',
  'promo.subtitle': 'Promotion ROI Analysis',
  'promo.totalPrograms': 'Tổng chương trình',
  'promo.running': 'đang chạy',
  'promo.totalCost': 'Tổng chi phí',
  'promo.totalRevenue': 'Tổng doanh thu',
  'promo.avgROI': 'ROI trung bình',
  'promo.noData': 'Chưa có dữ liệu khuyến mãi',
  'promo.noDataDesc': 'Tạo chương trình khuyến mãi để theo dõi hiệu quả',
  'promo.topPerformer': 'Top Performer',
  'promo.needsImprovement': 'Cần cải thiện',
  'promo.costPerOrder': 'Chi phí/đơn',
  'promo.roiByProgram': 'ROI theo chương trình',
  'promo.roasVsRevenue': 'ROAS vs Doanh thu',
  'promo.revenueMillion': 'Doanh thu (tr)',
  'promo.programDetails': 'Chi tiết chương trình',
  'promo.programName': 'Tên chương trình',
  'promo.channel': 'Kênh',
  'promo.status': 'Trạng thái',
  'promo.cost': 'Chi phí',
  'promo.revenue': 'Doanh thu',
  'promo.progress': 'Tiến độ',
  'promo.statusActive': 'Đang chạy',
  'promo.statusEnded': 'Đã kết thúc',
  'promo.statusDraft': 'Nháp',
  'promo.statusCancelled': 'Đã hủy',

  // Supplier Payments
  'supplier.title': 'Tối ưu thanh toán NCC',
  'supplier.subtitle': 'Supplier Payment Optimization',
  'supplier.totalPayables': 'Tổng phải trả',
  'supplier.overdue': 'Quá hạn',
  'supplier.dueThisWeek': 'Đến hạn tuần này',
  'supplier.potentialSavings': 'Tiết kiệm tiềm năng',
  'supplier.avgDiscount': 'TB: chiết khấu',
  'supplier.noData': 'Chưa có lịch thanh toán',
  'supplier.noDataDesc': 'Thêm lịch thanh toán nhà cung cấp để tối ưu dòng tiền',
  'supplier.earlyPaymentRec': 'Đề xuất thanh toán sớm',
  'supplier.overduePayments': 'Thanh toán quá hạn',
  'supplier.allPending': 'Tất cả thanh toán chờ xử lý',
  'supplier.vendorName': 'Nhà cung cấp',
  'supplier.amount': 'Số tiền',
  'supplier.earlyDueDate': 'Hạn thanh toán sớm',
  'supplier.discount': 'Chiết khấu',
  'supplier.savings': 'Tiết kiệm',
  'supplier.dueDate': 'Ngày đến hạn',
  'supplier.recommendation': 'Đề xuất',
  'supplier.earlyDiscount': 'Chiết khấu sớm',
  'supplier.pay': 'Thanh toán',
  'supplier.payNow': 'Thanh toán ngay',
  'supplier.paidEarly': 'Thanh toán sớm',
  'supplier.paidOnTime': 'Đúng hạn',
  'supplier.paidLate': 'Trễ hạn',
  'supplier.overdueDays': 'Quá hạn',
  'supplier.daysLeft': 'Còn',
  'supplier.payEarly': 'Nên thanh toán sớm',
  'supplier.payOnDue': 'Thanh toán đúng hạn',
  'supplier.negotiate': 'Đàm phán',
};

// English translations
const en: Record<string, string> = {
  // Common
  'common.search': 'Search invoices, customers...',
  'common.loading': 'Loading...',
  'common.noData': 'No data',
  'common.save': 'Save',
  'common.cancel': 'Cancel',
  'common.delete': 'Delete',
  'common.edit': 'Edit',
  'common.add': 'Add',
  'common.view': 'View',
  'common.close': 'Close',
  'common.confirm': 'Confirm',
  'common.back': 'Back',
  'common.next': 'Next',
  'common.submit': 'Submit',
  'common.export': 'Export',
  'common.import': 'Import',
  'common.filter': 'Filter',
  'common.reset': 'Reset',
  'common.all': 'All',
  'common.status': 'Status',
  'common.actions': 'Actions',
  'common.date': 'Date',
  'common.amount': 'Amount',
  'common.total': 'Total',
  'common.details': 'Details',
  'common.settings': 'Settings',
  'common.help': 'Help',
  'common.logout': 'Sign out',

  // Header
  'header.alerts': 'Alerts',
  'header.unreadAlerts': 'unread alerts',
  'header.noAlerts': 'No alerts',
  'header.viewAllAlerts': 'View all alerts',
  'header.high': 'High',
  'header.medium': 'Medium',
  'header.low': 'Low',

  // Sidebar - Main navigation
  'nav.cfoOverview': 'CFO Overview',
  'nav.dashboard': 'Dashboard',
  'nav.cashForecast': 'Cash Flow Forecast',
  'nav.workingCapital': 'Working Capital Optimization',
  'nav.cashConversion': 'Cash Conversion Cycle',

  'nav.strategyDecision': 'Strategy & Decision',
  'nav.executiveSummary': 'Executive Summary',
  'nav.capitalAllocation': 'Capital Allocation',
  'nav.riskDashboard': 'Risk Dashboard',
  'nav.decisionSupport': 'Decision Support',

  'nav.financialReports': 'Financial Reports',
  'nav.plReport': 'P&L Report',
  'nav.analysis': 'Comprehensive Analysis',
  'nav.budgetVsActual': 'Budget vs Actual',
  'nav.varianceAnalysis': 'Variance Analysis',
  'nav.boardReports': 'Board Reports',

  'nav.planSimulation': 'Planning & Simulation',
  'nav.scenario': 'Scenario & What-If',
  'nav.rollingForecast': 'Rolling Forecast',
  'nav.strategicInitiatives': 'Strategic Initiatives',

  'nav.arAp': 'AR/AP',
  'nav.invoiceManagement': 'Invoice Management',
  'nav.arOperations': 'AR Operations',
  'nav.apOverview': 'AP Overview',
  'nav.creditDebitNotes': 'CN/DN Tracking',
  'nav.reconciliation': 'Reconciliation',

  'nav.salesChannels': 'Sales Channels',
  'nav.channelAnalytics': 'Channel Analytics',
  'nav.unitEconomics': 'Unit Economics',

  'nav.dataHub': 'Data Hub',
  'nav.dataCenter': 'Data Center',
  'nav.etlRules': 'ETL Rules',

  'nav.taxCompliance': 'Tax & Compliance',
  'nav.taxTracking': 'Tax Compliance',
  'nav.covenantTracking': 'Covenant Tracking',

  'nav.alerts': 'Alerts',

  'nav.admin': 'Administration',
  'nav.companyManagement': 'Company Management',
  'nav.members': 'Members',
  'nav.rbac': 'RBAC Permissions',
  'nav.auditLog': 'Activity Log',

  'nav.api': 'API',

  'nav.integrationGuide': 'Integration Guide',
  'nav.formulas': 'Formulas',
  'nav.formulasOverview': 'Formula Overview',
  'nav.formulaSettings': 'Formula Settings',
  'nav.superAdmin': 'Super Admin',
  'nav.tenantManagement': 'Tenant Management',
  'nav.userManagement': 'User Management',
  'nav.platformSettings': 'Platform Settings',

  // Auth
  'auth.signIn': 'Sign In',
  'auth.signUp': 'Sign Up',
  'auth.email': 'Email',
  'auth.password': 'Password',
  'auth.confirmPassword': 'Confirm Password',
  'auth.fullName': 'Full Name',
  'auth.forgotPassword': 'Forgot password?',
  'auth.noAccount': "Don't have an account?",
  'auth.hasAccount': 'Already have an account?',

  // Dashboard
  'dashboard.title': 'CFO Dashboard',
  'dashboard.totalRevenue': 'Total Revenue',
  'dashboard.netProfit': 'Net Profit',
  'dashboard.cashBalance': 'Cash Balance',
  'dashboard.accountsReceivable': 'Accounts Receivable',
  'dashboard.refreshData': 'Refresh Data',

  // Executive Summary
  'exec.subtitle': 'Financial overview for CEO/Board - real-time updates',
  'exec.healthScore': 'Financial Health Score',
  'exec.healthDescription': 'Financial health assessment across 6 dimensions',
  'exec.points': 'points',
  'exec.statusGood': 'Good',
  'exec.statusWarning': 'Average',
  'exec.statusCritical': 'Needs Improvement',
  'exec.goodMetrics': 'Good Metrics',
  'exec.needsMonitoring': 'Needs Monitoring',
  'exec.needsImprovement': 'Needs Improvement',
  'exec.revenueMTD': 'Revenue MTD',
  'exec.cashPosition': 'Cash Position',
  'exec.runway': 'Runway',
  'exec.months': 'months',
  'exec.minThreshold': 'Min threshold',
  'exec.target': 'target',
  'exec.quickWins': 'Quick Wins',
  'exec.quickWinsDesc': 'Savings/revenue opportunities - calculated from real data',
  'exec.noQuickWins': 'Excellent! No quick wins to handle',
  'exec.totalPotential': 'Total potential recovery',
  'exec.riskAlerts': 'Risk Alerts',
  'exec.riskAlertsDesc': 'Financial risks to watch',
  'exec.noRiskAlerts': 'No risk alerts',
  'exec.effortLow': 'Easy',
  'exec.effortMedium': 'Medium',
  'exec.effortHigh': 'Complex',
  'exec.reduceRisk': 'Reduce risk',
  // Health dimensions
  'exec.dimLiquidity': 'Liquidity',
  'exec.dimReceivables': 'Receivables',
  'exec.dimProfitability': 'Profitability',
  'exec.dimEfficiency': 'Efficiency',
  'exec.dimGrowth': 'Growth',
  'exec.dimStability': 'Stability',

  // Covenant Tracking
  'covenant.title': 'Covenant Tracking',
  'covenant.subtitle': 'Monitor financial covenant compliance with banks',
  'covenant.addCovenant': 'Add Covenant',
  'covenant.compliant': 'Compliant',
  'covenant.warning': 'Warning',
  'covenant.breached': 'Breached',
  'covenant.lender': 'Lender',
  'covenant.type': 'Type',
  'covenant.threshold': 'Threshold',
  'covenant.current': 'Current',
  'covenant.margin': 'Margin',
  'covenant.measurementHistory': 'Measurement History',

  // CFO Dashboard
  'cfo.title': 'Liquidity & Cash',
  'cfo.subtitle': 'Liquidity & Cash Overview',
  'cfo.pageTitle': 'CFO Overview | Bluecore Finance',
  'cfo.pageDesc': 'CFO Financial Dashboard - Liquidity, Cash, AR and Forecast',
  'cfo.refreshData': 'Refresh Data',
  'cfo.cashToday': 'Cash Today',
  'cfo.cashRunway': 'Cash Runway',
  'cfo.cashNext7Days': 'Cash Next 7 Days',
  'cfo.overdueAR': 'Total Overdue AR',
  'cfo.ccc': 'Cash Conversion Cycle',
  'cfo.days': 'days',
  'cfo.dso': 'DSO',
  'cfo.grossMargin': 'Gross Margin',
  'cfo.ebitdaMargin': 'EBITDA Margin',
  'cfo.ebitda': 'EBITDA',
  'cfo.thisPeriod': 'this period',
  'cfo.vsYesterday': 'vs yesterday',
  'cfo.burnPerMonth': 'burn/month (M)',
  'cfo.notEnoughData': 'Insufficient data',
  'cfo.chartError': 'Unable to load chart',

  // Cash Forecast
  'cashForecast.title': 'Cash Flow Forecast',
  'cashForecast.subtitle': 'Detailed cash flow forecast by day or week',
  'cashForecast.pageDesc': 'Daily and weekly cash flow forecast with AI insights and scenario analysis',
  'cashForecast.daily': 'Daily (90 days)',
  'cashForecast.weekly': 'Weekly (13 weeks)',

  // Cash Flow Direct
  'cashDirect.title': 'Direct Cash Flow',
  'cashDirect.subtitle': 'Direct Cash Flow Statement',
  'cashDirect.totalInflow': 'Total Inflows',
  'cashDirect.totalOutflow': 'Total Outflows',
  'cashDirect.netChange': 'Net Change',
  'cashDirect.runway': 'Cash Runway',
  'cashDirect.burnRate': 'Burn',
  'cashDirect.perMonth': '/month',
  'cashDirect.operating': 'Operating Activities',
  'cashDirect.investing': 'Investing Activities',
  'cashDirect.financing': 'Financing Activities',
  'cashDirect.noData': 'No cash flow data',
  'cashDirect.addData': 'Add cash flow reports to analyze',
  'cashDirect.chart': 'Chart',
  'cashDirect.detail': 'Details',
  'cashDirect.trendTitle': 'Cash Flow Trend by Period',
  'cashDirect.closingBalance': 'Closing Balance',
  'cashDirect.detailTitle': 'Cash Flow Details by Period',
  'cashDirect.period': 'Period',
  'cashDirect.type': 'Type',
  'cashDirect.actual': 'Actual',
  'cashDirect.forecast': 'Forecast',
  'cashDirect.fromCustomers': 'From Customers',
  'cashDirect.toSuppliers': 'To Suppliers',
  'cashDirect.toEmployees': 'To Employees',
  'cashDirect.cfOperating': 'Operating CF',
  'cashDirect.cfInvesting': 'Investing CF',
  'cashDirect.cfFinancing': 'Financing CF',
  'cashDirect.endingBalance': 'Ending Balance',
  'cashDirect.months': 'months',
  'cashDirect.million': 'M',

  // Working Capital
  'workingCapital.title': 'Working Capital Optimization',
  'workingCapital.subtitle': 'Analysis and optimization of Cash Conversion Cycle',
  'workingCapital.formulas': 'Formulas',
  'workingCapital.dso': 'DSO',
  'workingCapital.dsoFull': 'DSO (Days Sales Outstanding)',
  'workingCapital.dsoFormula': '= (Receivables / Revenue) × Days',
  'workingCapital.dsoDesc': 'Days to collect from customers',
  'workingCapital.dio': 'DIO',
  'workingCapital.dioFull': 'DIO (Days Inventory Outstanding)',
  'workingCapital.dioFormula': '= (Inventory / COGS) × Days',
  'workingCapital.dioDesc': 'Days inventory held before sale',
  'workingCapital.dpo': 'DPO',
  'workingCapital.dpoFull': 'DPO (Days Payable Outstanding)',
  'workingCapital.dpoFormula': '= (Payables / Purchases) × Days',
  'workingCapital.dpoDesc': 'Days to pay suppliers',
  'workingCapital.ccc': 'CCC (Cash Conversion Cycle)',
  'workingCapital.cccFormula': '= DSO + DIO - DPO',
  'workingCapital.days': 'days',
  'workingCapital.target': 'Target',
  'workingCapital.inventoryDays': 'Inventory days',
  'workingCapital.improving': 'Improving',
  'workingCapital.worsening': 'Worsening',
  'workingCapital.stable': 'Stable',
  'workingCapital.potentialRelease': 'Potential Capital Release',
  'workingCapital.ifTargetMet': 'If targets met',
  'workingCapital.cccAnalysis': 'CCC Analysis',
  'workingCapital.current': 'Current',
  'workingCapital.cccTrend': 'CCC Trend',
  'workingCapital.cccTrendDesc': 'Cash conversion cycle over time',
  'workingCapital.noTrendData': 'No trend data available',
  'workingCapital.ar': 'Accounts Receivable (AR)',
  'workingCapital.inventory': 'Inventory',
  'workingCapital.ap': 'Accounts Payable (AP)',
  'workingCapital.turnover': 'Turnover',
  'workingCapital.recommendations': 'Optimization Recommendations',
  'workingCapital.recommendationsDesc': 'Actions to improve working capital',

  // Cash Conversion Cycle
  'ccc.title': 'Cash Conversion Cycle (CCC)',
  'ccc.subtitle': 'Working capital cycle analysis: DSO + DIO - DPO',
  'ccc.loadError': 'Unable to load Cash Conversion Cycle data',
  'ccc.formulas': 'Formulas',
  'ccc.dsoDesc': 'Time to collect receivables',
  'ccc.dioDesc': 'Time inventory is held',
  'ccc.dpoDesc': 'Time to pay suppliers',
  'ccc.good': 'Good',
  'ccc.high': 'High',
  'ccc.low': 'Low',
  'ccc.vsIndustry': 'vs Industry',
  'ccc.betterBy': 'Better by',
  'ccc.slowerBy': 'Slower by',
  'ccc.industryBenchmark': 'Industry benchmark',
  'ccc.receivables': 'Receivables',
  'ccc.inventoryValue': 'Inventory',
  'ccc.payables': 'Payables',
  'ccc.benchmark': 'Benchmark',
  'ccc.trendTitle': 'CCC Trend',
  'ccc.trendDesc': 'Track components over time',
  'ccc.noTrendData': 'No trend data available',
  'ccc.wcImpact': 'Working Capital Impact',
  'ccc.wcImpactDesc': 'Working capital being tied up',
  'ccc.capitalTied': 'Capital Tied Up',

  // Inventory Aging
  'inventory.title': 'Inventory Aging Analysis',
  'inventory.subtitle': 'Inventory Aging Analysis',
  'inventory.totalSKU': 'Total SKU',
  'inventory.totalValue': 'Total Value',
  'inventory.avgAge': 'Avg Age',
  'inventory.days': 'days',
  'inventory.slowMoving': 'Slow Moving (>90 days)',
  'inventory.noData': 'No inventory data',
  'inventory.noDataDesc': 'Import inventory data to view aging analysis',
  'inventory.valueByAge': 'Value Distribution by Age',
  'inventory.qtyValueByBucket': 'Quantity & Value by Bucket',
  'inventory.quantity': 'Quantity',
  'inventory.valueMillion': 'Value (M)',
  'inventory.detailByAge': 'Details by Age Group',
  'inventory.slowMovingItems': 'Slow Moving Items (>90 days)',
  'inventory.sku': 'SKU',
  'inventory.productName': 'Product Name',
  'inventory.category': 'Category',
  'inventory.value': 'Value',
  'inventory.ageDays': 'Age (days)',

  // Promotion ROI
  'promo.title': 'Promotion ROI',
  'promo.subtitle': 'Promotion ROI Analysis',
  'promo.totalPrograms': 'Total Programs',
  'promo.running': 'running',
  'promo.totalCost': 'Total Cost',
  'promo.totalRevenue': 'Total Revenue',
  'promo.avgROI': 'Average ROI',
  'promo.noData': 'No promotion data',
  'promo.noDataDesc': 'Create promotions to track effectiveness',
  'promo.topPerformer': 'Top Performer',
  'promo.needsImprovement': 'Needs Improvement',
  'promo.costPerOrder': 'Cost/Order',
  'promo.roiByProgram': 'ROI by Program',
  'promo.roasVsRevenue': 'ROAS vs Revenue',
  'promo.revenueMillion': 'Revenue (M)',
  'promo.programDetails': 'Program Details',
  'promo.programName': 'Program Name',
  'promo.channel': 'Channel',
  'promo.status': 'Status',
  'promo.cost': 'Cost',
  'promo.revenue': 'Revenue',
  'promo.progress': 'Progress',
  'promo.statusActive': 'Active',
  'promo.statusEnded': 'Ended',
  'promo.statusDraft': 'Draft',
  'promo.statusCancelled': 'Cancelled',

  // Supplier Payments
  'supplier.title': 'Supplier Payment Optimization',
  'supplier.subtitle': 'Supplier Payment Optimization',
  'supplier.totalPayables': 'Total Payables',
  'supplier.overdue': 'Overdue',
  'supplier.dueThisWeek': 'Due This Week',
  'supplier.potentialSavings': 'Potential Savings',
  'supplier.avgDiscount': 'Avg: discount',
  'supplier.noData': 'No payment schedule',
  'supplier.noDataDesc': 'Add supplier payment schedules to optimize cash flow',
  'supplier.earlyPaymentRec': 'Early Payment Recommendations',
  'supplier.overduePayments': 'Overdue Payments',
  'supplier.allPending': 'All Pending Payments',
  'supplier.vendorName': 'Supplier',
  'supplier.amount': 'Amount',
  'supplier.earlyDueDate': 'Early Payment Date',
  'supplier.discount': 'Discount',
  'supplier.savings': 'Savings',
  'supplier.dueDate': 'Due Date',
  'supplier.recommendation': 'Recommendation',
  'supplier.earlyDiscount': 'Early Discount',
  'supplier.pay': 'Pay',
  'supplier.payNow': 'Pay Now',
  'supplier.paidEarly': 'Paid Early',
  'supplier.paidOnTime': 'On Time',
  'supplier.paidLate': 'Late',
  'supplier.overdueDays': 'Overdue',
  'supplier.daysLeft': 'Left',
  'supplier.payEarly': 'Pay Early',
  'supplier.payOnDue': 'Pay On Due',
  'supplier.negotiate': 'Negotiate',
};

const translations: Record<Language, Record<string, string>> = { vi, en };

interface LanguageProviderProps {
  children: ReactNode;
}

export function LanguageProvider({ children }: LanguageProviderProps) {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('app-language');
    return (saved as Language) || 'vi';
  });

  useEffect(() => {
    localStorage.setItem('app-language', language);
    document.documentElement.lang = language;
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
