/**
 * Hook for seeding and managing multi-channel alert rules
 * Provides default alert rules for retail operations across multiple sales channels
 */

import { useMutation, useQueryClient } from '@tanstack/react-query';
import { supabase } from '@/integrations/supabase/client';
import { toast } from 'sonner';
import { useActiveTenantId } from './useActiveTenantId';
import type { SalesChannel, AlertGroup } from './useIntelligentAlertRules';

interface AlertRuleTemplate {
  rule_code: string;
  rule_name: string;
  description: string;
  rule_category: string;
  severity: 'critical' | 'warning' | 'info';
  threshold_config: Record<string, any>;
  calculation_formula: string;
  suggested_actions: string[];
  applicable_channels: SalesChannel[];
  alert_group: AlertGroup;
  priority_order: number;
}

// ========== DEFAULT ALERT RULES TEMPLATES ==========

export const defaultAlertRuleTemplates: AlertRuleTemplate[] = [
  // ========== FULFILLMENT & VẬN CHUYỂN ==========
  {
    rule_code: 'ORDER_DELIVERY_DELAYED',
    rule_name: 'Đơn giao chậm',
    description: 'Đơn hàng vượt SLA giao hàng của sàn TMĐT, có nguy cơ bị phạt hoặc ảnh hưởng rating shop',
    rule_category: 'fulfillment',
    severity: 'critical',
    threshold_config: { metric: 'delivery_sla_days', operator: 'greater_than', value: 0, unit: 'days' },
    calculation_formula: 'delivery_days - platform_sla_days',
    suggested_actions: ['Liên hệ ĐVVC kiểm tra trạng thái', 'Cân nhắc chuyển đơn vị khác', 'Giao trực tiếp nếu cần'],
    applicable_channels: ['shopee', 'lazada', 'tiktok'],
    alert_group: 'fulfillment',
    priority_order: 1,
  },
  {
    rule_code: 'ORDER_NOT_SHIPPED_24H',
    rule_name: 'Đơn chưa xuất kho >24h',
    description: 'Đơn hàng đã xác nhận nhưng chưa giao cho đơn vị vận chuyển quá 24 giờ',
    rule_category: 'fulfillment',
    severity: 'critical',
    threshold_config: { metric: 'hours_since_confirmed', operator: 'greater_than', value: 24, unit: 'hours' },
    calculation_formula: 'NOW() - order_confirmed_at',
    suggested_actions: ['Kiểm tra tồn kho và năng lực đóng gói', 'Ưu tiên xử lý ngay'],
    applicable_channels: ['shopee', 'lazada', 'tiktok', 'website', 'social'],
    alert_group: 'fulfillment',
    priority_order: 2,
  },
  {
    rule_code: 'RETURN_NOT_COLLECTED',
    rule_name: 'Hàng hoàn chưa lấy về',
    description: 'Đơn hoàn trả nhưng chưa được nhập kho lại sau 3 ngày',
    rule_category: 'fulfillment',
    severity: 'warning',
    threshold_config: { metric: 'days_since_return', operator: 'greater_than', value: 3, unit: 'days' },
    calculation_formula: 'NOW() - return_created_at',
    suggested_actions: ['Liên hệ ĐVVC lấy hàng hoàn', 'Kiểm tra trạng thái trên sàn'],
    applicable_channels: ['shopee', 'lazada', 'tiktok'],
    alert_group: 'fulfillment',
    priority_order: 3,
  },
  {
    rule_code: 'ORDER_SURGE_ALERT',
    rule_name: 'Đơn tăng đột biến',
    description: 'Số đơn/giờ vượt 150% năng lực xử lý kho',
    rule_category: 'fulfillment',
    severity: 'warning',
    threshold_config: { metric: 'orders_per_hour_ratio', operator: 'greater_than', value: 150, unit: 'percentage' },
    calculation_formula: '(current_orders_per_hour / warehouse_capacity_per_hour) * 100',
    suggested_actions: ['Tăng cường nhân sự đóng gói', 'Thông báo team kho chuẩn bị OT', 'Tạm dừng promotion nếu cần'],
    applicable_channels: ['shopee', 'lazada', 'tiktok', 'website', 'social', 'pos'],
    alert_group: 'fulfillment',
    priority_order: 4,
  },
  {
    rule_code: 'SHIPPING_COST_SPIKE',
    rule_name: 'Chi phí ship tăng bất thường',
    description: 'Chi phí vận chuyển/đơn tăng >20% so với tuần trước',
    rule_category: 'fulfillment',
    severity: 'warning',
    threshold_config: { metric: 'shipping_cost_change', operator: 'greater_than', value: 20, unit: 'percentage' },
    calculation_formula: '((current_avg - prev_avg) / prev_avg) * 100',
    suggested_actions: ['Kiểm tra cơ cấu ĐVVC', 'Đàm phán lại giá với carrier'],
    applicable_channels: ['shopee', 'lazada', 'tiktok', 'website', 'social'],
    alert_group: 'fulfillment',
    priority_order: 5,
  },
  {
    rule_code: 'CARRIER_DELAY_PATTERN',
    rule_name: 'ĐVVC giao chậm liên tục',
    description: 'Một ĐVVC có tỷ lệ giao trễ >15% trong tuần',
    rule_category: 'fulfillment',
    severity: 'warning',
    threshold_config: { metric: 'carrier_delay_rate', operator: 'greater_than', value: 15, unit: 'percentage' },
    calculation_formula: '(delayed_orders / total_orders_by_carrier) * 100',
    suggested_actions: ['Giảm tỷ trọng đơn cho ĐVVC này', 'Liên hệ đàm phán SLA'],
    applicable_channels: ['shopee', 'lazada', 'tiktok', 'website', 'social'],
    alert_group: 'fulfillment',
    priority_order: 6,
  },
  {
    rule_code: 'COD_NOT_RECEIVED',
    rule_name: 'COD chưa đối soát',
    description: 'Tiền COD chưa nhận sau 7 ngày giao',
    rule_category: 'fulfillment',
    severity: 'warning',
    threshold_config: { metric: 'days_since_delivered', operator: 'greater_than', value: 7, unit: 'days' },
    calculation_formula: 'NOW() - order_delivered_at',
    suggested_actions: ['Liên hệ sàn/ĐVVC kiểm tra', 'Tạo ticket hỗ trợ'],
    applicable_channels: ['shopee', 'lazada', 'tiktok'],
    alert_group: 'fulfillment',
    priority_order: 7,
  },
  {
    rule_code: 'FAILED_DELIVERY_HIGH',
    rule_name: 'Tỷ lệ giao thất bại cao',
    description: 'Tỷ lệ giao thất bại >10% trong ngày',
    rule_category: 'fulfillment',
    severity: 'critical',
    threshold_config: { metric: 'failed_delivery_rate', operator: 'greater_than', value: 10, unit: 'percentage' },
    calculation_formula: '(failed_deliveries / total_deliveries) * 100',
    suggested_actions: ['Phân tích nguyên nhân', 'Cải thiện thông tin liên hệ KH', 'Đổi ĐVVC cho vùng có vấn đề'],
    applicable_channels: ['shopee', 'lazada', 'tiktok', 'website', 'social'],
    alert_group: 'fulfillment',
    priority_order: 8,
  },

  // ========== TỒN KHO & HÀNG HÓA ==========
  {
    rule_code: 'STOCKOUT_IMMINENT',
    rule_name: 'Sắp hết hàng',
    description: 'Tồn kho < số ngày dự trữ an toàn',
    rule_category: 'inventory',
    severity: 'critical',
    threshold_config: { metric: 'days_of_stock', operator: 'less_than', value: 7, unit: 'days' },
    calculation_formula: 'current_stock / avg_daily_sales',
    suggested_actions: ['Đặt hàng NCC ngay', 'Tạm ẩn sản phẩm nếu không kịp nhập'],
    applicable_channels: ['shopee', 'lazada', 'tiktok', 'website', 'social', 'pos'],
    alert_group: 'inventory',
    priority_order: 10,
  },
  {
    rule_code: 'INVENTORY_SYNC_MISMATCH',
    rule_name: 'Tồn kho lệch giữa các kênh',
    description: 'Số liệu tồn kho khác nhau giữa sàn và hệ thống',
    rule_category: 'inventory',
    severity: 'critical',
    threshold_config: { metric: 'inventory_difference', operator: 'greater_than', value: 0, unit: 'count' },
    calculation_formula: 'ABS(system_stock - platform_stock)',
    suggested_actions: ['Đồng bộ lại tồn kho ngay', 'Kiểm tra log sync'],
    applicable_channels: ['shopee', 'lazada', 'tiktok'],
    alert_group: 'inventory',
    priority_order: 11,
  },
  {
    rule_code: 'DEAD_STOCK_30_DAYS',
    rule_name: 'Hàng tồn >30 ngày không bán',
    description: 'SKU không có giao dịch trong 30 ngày',
    rule_category: 'inventory',
    severity: 'warning',
    threshold_config: { metric: 'days_without_sale', operator: 'greater_than', value: 30, unit: 'days' },
    calculation_formula: 'NOW() - last_sale_date',
    suggested_actions: ['Chạy promotion thanh lý', 'Combo với SP bán chạy', 'Điều chuyển sang kênh khác'],
    applicable_channels: ['shopee', 'lazada', 'tiktok', 'website', 'social', 'pos'],
    alert_group: 'inventory',
    priority_order: 12,
  },
  {
    rule_code: 'OVERSTOCK_WARNING',
    rule_name: 'Tồn quá mức',
    description: 'Tồn kho > 90 ngày bán',
    rule_category: 'inventory',
    severity: 'warning',
    threshold_config: { metric: 'days_of_stock', operator: 'greater_than', value: 90, unit: 'days' },
    calculation_formula: 'current_stock / avg_daily_sales',
    suggested_actions: ['Giảm đơn hàng NCC', 'Tăng promotion', 'Điều chuyển kênh'],
    applicable_channels: ['shopee', 'lazada', 'tiktok', 'website', 'social', 'pos'],
    alert_group: 'inventory',
    priority_order: 13,
  },
  {
    rule_code: 'EXPIRY_APPROACHING',
    rule_name: 'Hàng gần hết date',
    description: 'Sản phẩm còn <30 ngày đến HSD',
    rule_category: 'inventory',
    severity: 'warning',
    threshold_config: { metric: 'days_to_expiry', operator: 'less_than', value: 30, unit: 'days' },
    calculation_formula: 'expiry_date - NOW()',
    suggested_actions: ['Ưu tiên xuất trước (FEFO)', 'Chạy flash sale', 'Donate nếu còn ít'],
    applicable_channels: ['pos', 'website'],
    alert_group: 'inventory',
    priority_order: 14,
  },
  {
    rule_code: 'NEGATIVE_STOCK',
    rule_name: 'Tồn kho âm',
    description: 'Số lượng tồn < 0 (lỗi data)',
    rule_category: 'inventory',
    severity: 'critical',
    threshold_config: { metric: 'stock_quantity', operator: 'less_than', value: 0, unit: 'count' },
    calculation_formula: 'current_stock',
    suggested_actions: ['Kiểm tra lịch sử giao dịch', 'Điều chỉnh tồn kho', 'Fix nguyên nhân gốc'],
    applicable_channels: ['shopee', 'lazada', 'tiktok', 'website', 'social', 'pos'],
    alert_group: 'inventory',
    priority_order: 15,
  },
  {
    rule_code: 'REORDER_POINT_HIT',
    rule_name: 'Đến điểm đặt hàng',
    description: 'Tồn kho chạm mức cần đặt NCC',
    rule_category: 'inventory',
    severity: 'info',
    threshold_config: { metric: 'stock_vs_reorder', operator: 'less_than_or_equal', value: 0, unit: 'count' },
    calculation_formula: 'current_stock - reorder_point',
    suggested_actions: ['Tạo PO cho NCC', 'Kiểm tra lead time'],
    applicable_channels: ['shopee', 'lazada', 'tiktok', 'website', 'social', 'pos'],
    alert_group: 'inventory',
    priority_order: 16,
  },
  {
    rule_code: 'SLOW_MOVING_TO_FAST',
    rule_name: 'Hàng chậm bán đột ngột tăng',
    description: 'SKU slow-moving có velocity tăng 3x',
    rule_category: 'inventory',
    severity: 'info',
    threshold_config: { metric: 'velocity_change', operator: 'greater_than', value: 300, unit: 'percentage' },
    calculation_formula: '(current_velocity / previous_velocity) * 100',
    suggested_actions: ['Tăng tồn kho cho SP này', 'Phân tích nguyên nhân để nhân rộng'],
    applicable_channels: ['shopee', 'lazada', 'tiktok', 'website', 'social', 'pos'],
    alert_group: 'inventory',
    priority_order: 17,
  },

  // ========== DOANH THU & BIÊN LỢI NHUẬN ==========
  {
    rule_code: 'REVENUE_DROP_DAILY',
    rule_name: 'Doanh thu ngày giảm mạnh',
    description: 'Doanh thu giảm >30% so với cùng ngày tuần trước',
    rule_category: 'revenue',
    severity: 'critical',
    threshold_config: { metric: 'revenue_change', operator: 'less_than', value: -30, unit: 'percentage' },
    calculation_formula: '((today - same_day_last_week) / same_day_last_week) * 100',
    suggested_actions: ['Phân tích traffic và conversion', 'Kiểm tra vấn đề kỹ thuật', 'Tăng promotion'],
    applicable_channels: ['shopee', 'lazada', 'tiktok', 'website', 'social', 'pos'],
    alert_group: 'revenue',
    priority_order: 20,
  },
  {
    rule_code: 'MARGIN_NEGATIVE',
    rule_name: 'Biên lợi nhuận âm',
    description: 'SP/đơn hàng có margin < 0',
    rule_category: 'revenue',
    severity: 'critical',
    threshold_config: { metric: 'gross_margin', operator: 'less_than', value: 0, unit: 'percentage' },
    calculation_formula: '((selling_price - cost - fees) / selling_price) * 100',
    suggested_actions: ['Điều chỉnh giá bán', 'Giảm chi phí', 'Ngừng bán nếu không cải thiện'],
    applicable_channels: ['shopee', 'lazada', 'tiktok', 'website', 'social', 'pos'],
    alert_group: 'revenue',
    priority_order: 21,
  },
  {
    rule_code: 'DISCOUNT_ABUSE',
    rule_name: 'Lạm dụng khuyến mãi',
    description: 'Khách dùng quá nhiều mã giảm giá',
    rule_category: 'revenue',
    severity: 'warning',
    threshold_config: { metric: 'discount_frequency', operator: 'greater_than', value: 5, unit: 'count' },
    calculation_formula: 'COUNT(voucher_used) GROUP BY customer',
    suggested_actions: ['Block tài khoản khả nghi', 'Điều chỉnh điều kiện voucher'],
    applicable_channels: ['website', 'social'],
    alert_group: 'revenue',
    priority_order: 22,
  },
  {
    rule_code: 'AOV_DROP',
    rule_name: 'Giá trị đơn TB giảm',
    description: 'AOV giảm >15% trong tuần',
    rule_category: 'revenue',
    severity: 'warning',
    threshold_config: { metric: 'aov_change', operator: 'less_than', value: -15, unit: 'percentage' },
    calculation_formula: '((current_aov - prev_aov) / prev_aov) * 100',
    suggested_actions: ['Thiết kế bundle/combo', 'Tăng free shipping threshold', 'Upsell SP bổ sung'],
    applicable_channels: ['shopee', 'lazada', 'tiktok', 'website', 'social', 'pos'],
    alert_group: 'revenue',
    priority_order: 23,
  },
  {
    rule_code: 'PROMOTION_OVERSPEND',
    rule_name: 'Chi phí KM vượt ngân sách',
    description: 'Chi phí promotion >110% budget',
    rule_category: 'revenue',
    severity: 'warning',
    threshold_config: { metric: 'promotion_budget_usage', operator: 'greater_than', value: 110, unit: 'percentage' },
    calculation_formula: '(actual_cost / budget) * 100',
    suggested_actions: ['Tạm dừng/giảm khuyến mãi', 'Review hiệu quả campaign'],
    applicable_channels: ['shopee', 'lazada', 'tiktok', 'website', 'social', 'pos'],
    alert_group: 'revenue',
    priority_order: 24,
  },
  {
    rule_code: 'PLATFORM_FEE_INCREASE',
    rule_name: 'Phí sàn tăng',
    description: 'Phí commission sàn tăng bất thường',
    rule_category: 'revenue',
    severity: 'info',
    threshold_config: { metric: 'platform_fee_change', operator: 'greater_than', value: 10, unit: 'percentage' },
    calculation_formula: '((current_fee - prev_fee) / prev_fee) * 100',
    suggested_actions: ['Cập nhật pricing strategy', 'Tính lại margin', 'Cân nhắc tăng giá'],
    applicable_channels: ['shopee', 'lazada', 'tiktok'],
    alert_group: 'revenue',
    priority_order: 25,
  },
  {
    rule_code: 'CHANNEL_REVENUE_IMBALANCE',
    rule_name: 'Doanh thu lệch kênh',
    description: 'Một kênh chiếm >70% tổng doanh thu',
    rule_category: 'revenue',
    severity: 'warning',
    threshold_config: { metric: 'channel_revenue_share', operator: 'greater_than', value: 70, unit: 'percentage' },
    calculation_formula: '(channel_revenue / total_revenue) * 100',
    suggested_actions: ['Đầu tư phát triển kênh khác', 'Đa dạng hóa nguồn doanh thu'],
    applicable_channels: ['shopee', 'lazada', 'tiktok', 'website', 'social', 'pos'],
    alert_group: 'revenue',
    priority_order: 26,
  },
  {
    rule_code: 'CASH_FLOW_WARNING',
    rule_name: 'Dòng tiền căng',
    description: 'Tiền mặt < chi phí 7 ngày tới',
    rule_category: 'revenue',
    severity: 'critical',
    threshold_config: { metric: 'cash_coverage_days', operator: 'less_than', value: 7, unit: 'days' },
    calculation_formula: 'current_cash / avg_daily_expenses',
    suggested_actions: ['Thu hồi công nợ gấp', 'Đàm phán giãn thanh toán NCC', 'Vay ngắn hạn'],
    applicable_channels: ['shopee', 'lazada', 'tiktok', 'website', 'social', 'pos'],
    alert_group: 'revenue',
    priority_order: 27,
  },

  // ========== CHẤT LƯỢNG DỊCH VỤ ==========
  {
    rule_code: 'NEGATIVE_REVIEW_SPIKE',
    rule_name: 'Đánh giá xấu tăng',
    description: 'Đánh giá 1-2 sao tăng >50% trong tuần',
    rule_category: 'service',
    severity: 'critical',
    threshold_config: { metric: 'negative_review_change', operator: 'greater_than', value: 50, unit: 'percentage' },
    calculation_formula: '((this_week - last_week) / last_week) * 100',
    suggested_actions: ['Phân tích nội dung đánh giá', 'Liên hệ KH xin feedback', 'Cải thiện SP/DV'],
    applicable_channels: ['shopee', 'lazada', 'tiktok'],
    alert_group: 'service',
    priority_order: 30,
  },
  {
    rule_code: 'RESPONSE_TIME_SLOW',
    rule_name: 'Phản hồi chat chậm',
    description: 'Thời gian phản hồi TB >15 phút',
    rule_category: 'service',
    severity: 'warning',
    threshold_config: { metric: 'avg_response_minutes', operator: 'greater_than', value: 15, unit: 'minutes' },
    calculation_formula: 'AVG(first_response_time - message_received_time)',
    suggested_actions: ['Tăng nhân sự CSKH', 'Sử dụng chatbot', 'Set up auto-reply'],
    applicable_channels: ['shopee', 'lazada', 'tiktok', 'social'],
    alert_group: 'service',
    priority_order: 31,
  },
  {
    rule_code: 'COMPLAINT_PENDING',
    rule_name: 'Khiếu nại chưa xử lý',
    description: 'Ticket mở >48h chưa giải quyết',
    rule_category: 'service',
    severity: 'warning',
    threshold_config: { metric: 'hours_since_opened', operator: 'greater_than', value: 48, unit: 'hours' },
    calculation_formula: 'NOW() - ticket_created_at',
    suggested_actions: ['Ưu tiên xử lý ngay', 'Escalate lên cấp cao hơn'],
    applicable_channels: ['shopee', 'lazada', 'tiktok', 'website', 'social', 'pos'],
    alert_group: 'service',
    priority_order: 32,
  },
  {
    rule_code: 'REFUND_RATE_HIGH',
    rule_name: 'Tỷ lệ hoàn tiền cao',
    description: 'Tỷ lệ refund >5% trong tuần',
    rule_category: 'service',
    severity: 'warning',
    threshold_config: { metric: 'refund_rate', operator: 'greater_than', value: 5, unit: 'percentage' },
    calculation_formula: '(refunded_orders / total_orders) * 100',
    suggested_actions: ['Phân tích nguyên nhân', 'Cải thiện mô tả SP', 'Tăng QC trước khi gửi'],
    applicable_channels: ['shopee', 'lazada', 'tiktok', 'website', 'social', 'pos'],
    alert_group: 'service',
    priority_order: 33,
  },
  {
    rule_code: 'PRODUCT_QUALITY_ISSUE',
    rule_name: 'Lỗi chất lượng sản phẩm',
    description: 'Nhiều khiếu nại cùng 1 SKU về chất lượng',
    rule_category: 'service',
    severity: 'critical',
    threshold_config: { metric: 'quality_complaints', operator: 'greater_than', value: 3, unit: 'count' },
    calculation_formula: 'COUNT(complaints) WHERE type = quality GROUP BY sku',
    suggested_actions: ['Tạm dừng bán SP', 'Kiểm tra lô hàng', 'Liên hệ NCC', 'Thu hồi nếu nghiêm trọng'],
    applicable_channels: ['shopee', 'lazada', 'tiktok', 'website', 'social', 'pos'],
    alert_group: 'service',
    priority_order: 34,
  },
  {
    rule_code: 'STORE_RATING_DROP',
    rule_name: 'Điểm shop giảm',
    description: 'Rating shop < ngưỡng yêu cầu sàn',
    rule_category: 'service',
    severity: 'critical',
    threshold_config: { metric: 'store_rating', operator: 'less_than', value: 4.5, unit: 'score' },
    calculation_formula: 'current_store_rating',
    suggested_actions: ['Cải thiện các chỉ số ảnh hưởng rating', 'Follow-up KH đánh giá tốt'],
    applicable_channels: ['shopee', 'lazada', 'tiktok'],
    alert_group: 'service',
    priority_order: 35,
  },
  {
    rule_code: 'PENALTY_WARNING',
    rule_name: 'Cảnh báo vi phạm sàn',
    description: 'Shop nhận cảnh cáo/phạt từ sàn',
    rule_category: 'service',
    severity: 'critical',
    threshold_config: { metric: 'penalty_count', operator: 'greater_than', value: 0, unit: 'count' },
    calculation_formula: 'COUNT(penalties) WHERE status = active',
    suggested_actions: ['Đọc kỹ nội dung vi phạm', 'Khắc phục ngay', 'Gửi khiếu nại nếu bị oan'],
    applicable_channels: ['shopee', 'lazada', 'tiktok'],
    alert_group: 'service',
    priority_order: 36,
  },

  // ========== ĐẶC THÙ SÀN TMĐT ==========
  {
    rule_code: 'PLATFORM_API_SYNC_FAILED',
    rule_name: 'Lỗi đồng bộ sàn',
    description: 'API kết nối sàn bị lỗi >30 phút',
    rule_category: 'operations',
    severity: 'critical',
    threshold_config: { metric: 'minutes_since_last_sync', operator: 'greater_than', value: 30, unit: 'minutes' },
    calculation_formula: 'NOW() - last_successful_sync',
    suggested_actions: ['Kiểm tra API credentials', 'Retry sync', 'Liên hệ support sàn'],
    applicable_channels: ['shopee', 'lazada', 'tiktok'],
    alert_group: 'operations',
    priority_order: 40,
  },
  {
    rule_code: 'FLASH_SALE_STOCK_LOW',
    rule_name: 'Hết hàng Flash Sale',
    description: 'Tồn kho Flash Sale còn <10%',
    rule_category: 'operations',
    severity: 'warning',
    threshold_config: { metric: 'flash_sale_stock_percent', operator: 'less_than', value: 10, unit: 'percentage' },
    calculation_formula: '(remaining / initial) * 100',
    suggested_actions: ['Bổ sung stock nếu còn thời gian', 'Chuẩn bị communication'],
    applicable_channels: ['shopee', 'lazada', 'tiktok'],
    alert_group: 'operations',
    priority_order: 41,
  },
  {
    rule_code: 'LISTING_DEACTIVATED',
    rule_name: 'Sản phẩm bị ẩn',
    description: 'SP bị sàn ẩn do vi phạm/hết hàng',
    rule_category: 'operations',
    severity: 'warning',
    threshold_config: { metric: 'deactivated_listings', operator: 'greater_than', value: 0, unit: 'count' },
    calculation_formula: 'COUNT(listings) WHERE status = deactivated',
    suggested_actions: ['Kiểm tra nguyên nhân', 'Cập nhật stock hoặc sửa vi phạm'],
    applicable_channels: ['shopee', 'lazada', 'tiktok'],
    alert_group: 'operations',
    priority_order: 42,
  },
  {
    rule_code: 'CAMPAIGN_ENDING_SOON',
    rule_name: 'Campaign sắp kết thúc',
    description: 'Chương trình KM còn <24h',
    rule_category: 'operations',
    severity: 'info',
    threshold_config: { metric: 'hours_to_campaign_end', operator: 'less_than', value: 24, unit: 'hours' },
    calculation_formula: 'campaign_end_time - NOW()',
    suggested_actions: ['Communication push cuối', 'Review kết quả để plan tiếp'],
    applicable_channels: ['shopee', 'lazada', 'tiktok'],
    alert_group: 'operations',
    priority_order: 43,
  },

  // ========== ĐẶC THÙ WEBSITE/APP ==========
  {
    rule_code: 'CART_ABANDON_HIGH',
    rule_name: 'Bỏ giỏ hàng cao',
    description: 'Tỷ lệ abandon cart >75%',
    rule_category: 'operations',
    severity: 'warning',
    threshold_config: { metric: 'cart_abandon_rate', operator: 'greater_than', value: 75, unit: 'percentage' },
    calculation_formula: '(abandoned / total_carts) * 100',
    suggested_actions: ['Tối ưu checkout flow', 'Thêm trust signals', 'Set up abandon cart email'],
    applicable_channels: ['website'],
    alert_group: 'operations',
    priority_order: 44,
  },
  {
    rule_code: 'CHECKOUT_FAILURE',
    rule_name: 'Lỗi thanh toán',
    description: 'Tỷ lệ checkout thất bại >5%',
    rule_category: 'operations',
    severity: 'critical',
    threshold_config: { metric: 'checkout_failure_rate', operator: 'greater_than', value: 5, unit: 'percentage' },
    calculation_formula: '(failed / total_checkouts) * 100',
    suggested_actions: ['Kiểm tra payment gateway', 'Test các phương thức', 'Liên hệ provider'],
    applicable_channels: ['website'],
    alert_group: 'operations',
    priority_order: 45,
  },
  {
    rule_code: 'TRAFFIC_SPIKE',
    rule_name: 'Traffic đột biến',
    description: 'Lượng truy cập tăng >200%',
    rule_category: 'operations',
    severity: 'info',
    threshold_config: { metric: 'traffic_change', operator: 'greater_than', value: 200, unit: 'percentage' },
    calculation_formula: '(current_hour / avg_hourly) * 100',
    suggested_actions: ['Kiểm tra server capacity', 'Scale up nếu cần', 'Tận dụng cơ hội convert'],
    applicable_channels: ['website'],
    alert_group: 'operations',
    priority_order: 46,
  },
  {
    rule_code: 'PAGE_LOAD_SLOW',
    rule_name: 'Website chậm',
    description: 'Page load >3 giây',
    rule_category: 'operations',
    severity: 'warning',
    threshold_config: { metric: 'page_load_seconds', operator: 'greater_than', value: 3, unit: 'seconds' },
    calculation_formula: 'AVG(page_load_time)',
    suggested_actions: ['Optimize images', 'Enable caching', 'Check server performance'],
    applicable_channels: ['website'],
    alert_group: 'operations',
    priority_order: 47,
  },

  // ========== ĐẶC THÙ CỬA HÀNG VẬT LÝ ==========
  {
    rule_code: 'STORE_NO_SALES_2H',
    rule_name: 'Cửa hàng không có đơn 2h',
    description: 'Không ghi nhận giao dịch trong 2 giờ',
    rule_category: 'operations',
    severity: 'warning',
    threshold_config: { metric: 'hours_without_sale', operator: 'greater_than', value: 2, unit: 'hours' },
    calculation_formula: 'NOW() - last_pos_transaction_time',
    suggested_actions: ['Kiểm tra POS có hoạt động', 'Liên hệ nhân viên cửa hàng'],
    applicable_channels: ['pos'],
    alert_group: 'operations',
    priority_order: 50,
  },
  {
    rule_code: 'POS_OFFLINE',
    rule_name: 'POS mất kết nối',
    description: 'Thiết bị POS offline >15 phút',
    rule_category: 'operations',
    severity: 'critical',
    threshold_config: { metric: 'minutes_offline', operator: 'greater_than', value: 15, unit: 'minutes' },
    calculation_formula: 'NOW() - last_heartbeat',
    suggested_actions: ['Kiểm tra mạng tại cửa hàng', 'Restart thiết bị', 'Chế độ offline nếu cần'],
    applicable_channels: ['pos'],
    alert_group: 'operations',
    priority_order: 51,
  },
  {
    rule_code: 'CASH_DISCREPANCY',
    rule_name: 'Chênh lệch tiền mặt',
    description: 'Tiền kiểm đếm khác hệ thống',
    rule_category: 'operations',
    severity: 'warning',
    threshold_config: { metric: 'cash_difference', operator: 'greater_than', value: 0, unit: 'amount' },
    calculation_formula: 'ABS(counted_cash - system_cash)',
    suggested_actions: ['Kiểm tra lại giao dịch', 'Đối chiếu hóa đơn', 'Báo cáo nếu chênh lệch lớn'],
    applicable_channels: ['pos'],
    alert_group: 'operations',
    priority_order: 52,
  },
  {
    rule_code: 'STORE_INVENTORY_LOW',
    rule_name: 'Tồn tại điểm thấp',
    description: 'SKU top-seller còn <5 SP tại cửa hàng',
    rule_category: 'inventory',
    severity: 'warning',
    threshold_config: { metric: 'store_stock', operator: 'less_than', value: 5, unit: 'count' },
    calculation_formula: 'store_stock WHERE is_top_seller = true',
    suggested_actions: ['Điều chuyển từ kho', 'Đặt hàng bổ sung'],
    applicable_channels: ['pos'],
    alert_group: 'inventory',
    priority_order: 53,
  },

  // ========== ĐẶC THÙ SOCIAL COMMERCE ==========
  {
    rule_code: 'MESSAGE_UNANSWERED',
    rule_name: 'Tin nhắn chưa trả lời',
    description: 'Tin nhắn chưa phản hồi >30 phút',
    rule_category: 'service',
    severity: 'warning',
    threshold_config: { metric: 'minutes_unanswered', operator: 'greater_than', value: 30, unit: 'minutes' },
    calculation_formula: 'NOW() - message_received_at',
    suggested_actions: ['Phản hồi ngay', 'Set up auto-reply ngoài giờ'],
    applicable_channels: ['social'],
    alert_group: 'service',
    priority_order: 54,
  },
  {
    rule_code: 'LIVE_SALE_ORDER_SURGE',
    rule_name: 'Đơn live tăng vọt',
    description: 'Đơn từ livestream vượt capacity',
    rule_category: 'fulfillment',
    severity: 'warning',
    threshold_config: { metric: 'live_orders_per_hour', operator: 'greater_than', value: 100, unit: 'count' },
    calculation_formula: 'COUNT(orders) WHERE source = livestream AND created_at > NOW() - 1 hour',
    suggested_actions: ['Tăng nhân sự nhận đơn', 'Chuẩn bị inventory', 'Thông báo KH về thời gian xử lý'],
    applicable_channels: ['social'],
    alert_group: 'fulfillment',
    priority_order: 55,
  },
  {
    rule_code: 'SOCIAL_MENTION_NEGATIVE',
    rule_name: 'Mention tiêu cực',
    description: 'Phát hiện bài viết/comment tiêu cực',
    rule_category: 'service',
    severity: 'warning',
    threshold_config: { metric: 'negative_mentions', operator: 'greater_than', value: 0, unit: 'count' },
    calculation_formula: 'COUNT(mentions) WHERE sentiment = negative',
    suggested_actions: ['Phản hồi chuyên nghiệp', 'Xử lý vấn đề KH', 'Escalate nếu viral risk'],
    applicable_channels: ['social'],
    alert_group: 'service',
    priority_order: 56,
  },
];

// ========== HOOKS ==========

export function useSeedAlertRules() {
  const { data: tenantId } = useActiveTenantId();
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async () => {
      if (!tenantId) throw new Error('No tenant ID');

      const rulesToInsert = defaultAlertRuleTemplates.map(template => ({
        tenant_id: tenantId,
        rule_code: template.rule_code,
        rule_name: template.rule_name,
        description: template.description,
        rule_category: template.rule_category,
        severity: template.severity,
        threshold_type: 'fixed',
        threshold_config: template.threshold_config,
        calculation_formula: template.calculation_formula,
        suggested_actions: template.suggested_actions,
        applicable_channels: template.applicable_channels,
        alert_group: template.alert_group,
        priority_order: template.priority_order,
        is_enabled: true,
        priority: template.priority_order,
        cooldown_hours: 4,
      }));

      const { data, error } = await supabase
        .from('intelligent_alert_rules')
        .upsert(rulesToInsert, { 
          onConflict: 'tenant_id,rule_code',
          ignoreDuplicates: false 
        })
        .select();

      if (error) throw error;
      return data;
    },
    onSuccess: (data) => {
      queryClient.invalidateQueries({ queryKey: ['intelligent-alert-rules'] });
      toast.success(`Đã tạo ${data?.length || 0} quy tắc cảnh báo`);
    },
    onError: (error) => {
      toast.error('Lỗi: ' + error.message);
    },
  });
}

export function useAlertRuleStats() {
  const { data: tenantId } = useActiveTenantId();

  return {
    getStatsByChannel: (rules: any[], channel: SalesChannel) => {
      const filtered = rules.filter(r => 
        r.applicable_channels?.includes(channel) || r.applicable_channels?.length === 0
      );
      return {
        total: filtered.length,
        enabled: filtered.filter(r => r.is_enabled).length,
        critical: filtered.filter(r => r.severity === 'critical' && r.is_enabled).length,
        warning: filtered.filter(r => r.severity === 'warning' && r.is_enabled).length,
      };
    },
    getStatsByGroup: (rules: any[], group: AlertGroup) => {
      const filtered = rules.filter(r => r.alert_group === group);
      return {
        total: filtered.length,
        enabled: filtered.filter(r => r.is_enabled).length,
        critical: filtered.filter(r => r.severity === 'critical' && r.is_enabled).length,
        warning: filtered.filter(r => r.severity === 'warning' && r.is_enabled).length,
      };
    },
  };
}
